baseURL = "/"
languageCode = "pt-br"
summaryLength = "10"
theme = "kross-hugo"
title = "Prêmio de Jornalismo de Dados"
[[menu.main]]
url = "ed21"
name = "ed21"
weight = 5
[[menu.main]]
URL = "contact"
name = "jornalismodedados.org"
url = "https://jornalismodedados.org"
weight = 4
[[menu.main]]
URL = "portfolio"
name = "portfolio"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "https://ok.org.br"
author = "Open Knowledge Brazil"
copyright = "Nosso conteúdo está disponível sob a licença Creative Commons Atribuição 4.0 Internacional, e pode ser compartilhado e reutilizado para trabalhos derivados, desde que citada a fonte."
description = "This is meta description"
email = "escoladedados@ok.org.br"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/logo.png"
phone = ""
theme_color = "#DC3332"
css = ["css/style.css"]


[params.contact]
enable = false
form_action = "#"



[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://twitter.com/escoladedados"
icon = "ti-twitter-alt"
[[params.social]]
URL = "#"
icon = "ti-linkedin"
[[params.social]]
URL = "https://instagram.com/openknowledgebrasil"
icon = "ti-instagram"
[[params.social]]
URL = "https://youtube.com/escoladedados"
icon = "ti-youtube"
