baseURL = "/"
languageCode = "pt-br"
summaryLength = "10"
theme = "kross-hugo"
title = "Prêmio de Jornalismo de Dados"

[[menu.main]]
name = "2021"
url = "ed21"
parent = "edições"
weight = 1
[[menu.main]]
name = "2020"
url = "ed21"
parent = "edições"
weight = 2
[[menu.main]]
name = "2019"
url = "ed21"
parent = "edições"
weight = 3
[[menu.main]]
url = "#"
name = "edições"
weight = 4
[[menu.main]]
url = "https://jornalismodedados.org"
name = "jornalismodedados.org"
weight = 5
[[menu.main]]
URL = "blog"
name = "Novidades"
weight = 2
[[menu.main]]
URL = "about"
name = "Sobre"
weight = 1
[params]
address = "https://escoladedados.org"
author = "Escola de Dados"
copyright = "Nosso conteúdo está disponível sob a licença Creative Commons Atribuição 4.0 Internacional, e pode ser compartilhado e reutilizado para trabalhos derivados, desde que citada a fonte."
description = "Site do Prêmio Cláudio Weber Abramo de Jornalismo de Dados"
email = "escoladedados@ok.org.br"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/logo.png"
phone = ""
theme_color = "#DC3332"
css = ["css/style.css"]

[params.contact]
enable = false
form_action = "#"



[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://twitter.com/escoladedados"
icon = "ti-twitter-alt"
[[params.social]]
URL = "https://www.linkedin.com/company/escola-de-dados"
icon = "ti-linkedin"
[[params.social]]
URL = "https://instagram.com/openknowledgebrasil"
icon = "ti-instagram"
[[params.social]]
URL = "https://youtube.com/escoladedados"
icon = "ti-youtube"
